# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  devopschallengesalesapidatabase:
    image: devopschallengesalesapidatabase
    build:
      context: .
      dockerfile: src/DevOpsChallenge.SalesApi.Database/Dockerfile
    ports:
      - 443
    depends_on: 
      - migrations
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - 14331:1433
    depends_on: 
      - migrations

  migrations:
    build: 
      context: .
      dockerfile: src/DevOpsChallenge.SalesApi/Dockerfile
